version: 2
updates:
- package-ecosystem: "uv"
  directory: "./"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
- package-ecosystem: "github-actions"
  directory: "/.github"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
- package-ecosystem: docker
  directory: "./"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
